Iter8
Perehodko/shortener-url pull request #11
Opened 2023-01-25 19:15 UTC by Perehodko

2023-01-26 23:30 UTC, Barugoo commented on cmd/shortener/main.go
> +		//w.Header().Set("Content-Encoding", "gzip")
Давай удалять закоменченный код из репозитория - если надо будет, мы его можем восстановить из истории коммитов

2023-01-26 23:31 UTC, Barugoo commented on cmd/shortener/main.go
> +			http.Error(w, err.Error(), 500)
Давай использовать константы которые нам сам пакет `net/http`:
```
http.Error(w, err.Error(), http.StatusInternalServerError)

2023-01-26 23:33 UTC, Barugoo commented on cmd/shortener/main.go
> +			panic(err)
Давай здесь тоже обработаем ошибку и вернем соответствующий статус клиенту (здесь это будет InternalServerError): мы никогда не паникуем в функциях участвующих в обработке запроса

2023-01-26 23:34 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Fatal(err)
Давай здесь обернем ошибку и пробросим наверх - а там уже зафаталим:
```go
if err := env.Parse(&cfg); err != nil {
    return fmt.Errorf("unable to parse env: %w", err)
}

2023-01-26 23:36 UTC, Barugoo commented on cmd/shortener/main.go
> +func Storage(flagf string) (storage.Storage, error) {
Давай назовем функцию `NewStorage` а то может показаться, что вызывая ее мы на самом деле приводим переменную к типу `Storage`
Аргумент лучше назвать `filename` - внутреннюю логику функции не должно интересовать, откуда это значение изначально пришло (тобишь флаг энв и тд)

2023-01-26 23:37 UTC, Barugoo commented on cmd/shortener/main.go
> +	err := env.Parse(&cfg)
Давай уберем вызов этой функции ближе к тому месту, где ты парсишь значения из флагов

2023-01-26 23:38 UTC, Barugoo commented on cmd/shortener/main.go
>  	}
Логику фоллбэка в виде подстановки значения из флага при пустом энве давай тоже утащим туда, где мы работаем с флагами

2023-01-26 23:40 UTC, Barugoo commented on cmd/shortener/main.go
> +			log.Fatalf("unable to create file storage: %v", err)
Тут лучше тоже эту ошибку пробросим вверх и зафаталим в `main` - иногда можно долго голову ломать, в каком конкретно месте у тебя прибивается процесс. Будет лучше если мы будем делать это всегда в одном месте - в функции `main`.
```go
return fmt.Errorf("unable to create file storage: %w", err)

2023-01-26 23:41 UTC, Barugoo commented on cmd/shortener/main.go
>  	r.Use(middleware.Recoverer)
Метод `r.Use` в библиотеке `chi` принимает variadic-аргумент, то бишь в нее можно передать произвольное количество значений одного типа через запятую:
```go
r.Use(
    middleware.RequestID,
    middleware.RealIP,
//...

2023-01-26 23:42 UTC, Barugoo commented on internal/middlewares/middlewares.go
> +		body, err := io.ReadAll(reader)
Не очень удобно, что для сжатых запросов мы с текущей реализацией дважды считываем тело - в gzipMiddleware и непосредственно в хэндлерах. Одна из прекрасных сторон пакета `io` это возможность наслаивать друг на друга `Reader`'ы (и `Writer`'ы) сколько угодно и затем вызвать один раз метод `Read` (`Write`) и все эти прослойки поочередно будут применяться к лежащему под капотом потоку байт.

Поэтому правильнее здесь было бы написать без вызова `io.ReadAll`:
```go
if r.Header.Get("Content-Encoding") == "gzip" {
	gz, err := gzip.NewReader(r.Body)
 	if err != nil {
 		http.Error(w, err.Error(), http.StatusInternalServerError)
 		return
 	}
 	// не забывайте потом закрыть *gzip.Reader
 	defer gz.Close()

        r.Body = gz
}
next.ServeHTTP(w, r)

2023-01-26 23:44 UTC, Barugoo requested changes
Привет! Отлично, но есть замечания, посмотри пожалуйста

2023-01-31 11:51 UTC, Barugoo commented on cmd/shortener/main.go
> +		}
Я об этом писал в предыдущих комментариях - все что касается логики наполнения конфига (выбор флага или энва как здесь) давай унесем поближе к инициализации этого самого конфига. Хэндлеры должны работать только с результатом этой инициализации - полями структуры `cfg`:
```go
BaseURL := cfg.BaseURL
shortURL := BaseURL + "/" + shortLink
```
или 
```go
shortURL := cfg.BaseURL + "/" + shortLink

2023-01-31 11:54 UTC, Barugoo commented on cmd/shortener/main.go
> +		return fileStorage, err
Тоже об этом уже писал - парсинг энвов для конфига логически не относится к инициализации хранилки, давай уберем его отсюда

2023-01-31 11:57 UTC, Barugoo commented on cmd/shortener/main.go
> +		}
Как это можно изобразить в `main`:
```go
// в main()
baseURL := flag.String("b", "http://localhost:8080", "BASE_URL из cl")
serverAddress := flag.String("a", ":8080", "SERVER_ADDRESS из cl")
fileStoragePath := flag.String("f", "store.json", "FILE_STORAGE_PATH из cl")
flag.Parse()

// вставляем в структуру cfg значения из флагов
cfg.ServerAddress = *serverAddress
cfg.BaseURL = *baseURL
cfg.FileName = *fileStoragePath

// перезатираем их значениями энвов
// если значения в энве для поля структуры нет - то в поле останется значение из флага
err := env.Parse(&cfg)
if err != nil {
    log.Fatal(err)
}

fileStorage, err := NewStorage(cfg.FileName)
if err != nil {
    log.Fatal(err)
}
//...

2023-01-31 11:59 UTC, Barugoo commented on cmd/shortener/main.go
> +	}
Кажется, что второй раз нам парсить энвы не нужно

2023-01-31 12:43 UTC, Barugoo commented on cmd/shortener/main.go
> +		if initialURL == "" {
Обычно, когда `err == nil` нам не нужно дополнительно валидировать результат - если функция отработала без ошибки то предполагается что она вернула нам ровно то, что мы ожидаем.

Если ты хочешь здесь проверить кейс отсутствия урла в хранилке, то тогда надо объявить ошибку в слое хранилки и ее пробрасывать из **_всех_** реализаций наружу, чтобы здесь ты могла ее поймать и эффективно различать ошибки работы базы от отсутствия значения в ней:
```go
initialURL, err := s.GetURL(shortURL)
if err != nil && !errors.Is(err, storage.ErrNotFound) {
    // кейс когда у нас база не работает по неизвестной причине логгируем
    log.Printf("unable to get url from db: %v", err)
    http.Error(w, "unable to get url from storage", http.StatusInternalServerError)
    return
}
if errors.Is(err, storage.ErrNotFound) {
    http.Error(w, "url not found", http.StatusNotFound)
    return
}

2023-01-31 12:43 UTC, Barugoo commented on cmd/shortener/main_test.go
> +//func TestNewStructRedirectTo(t *testing.T) {
Убираем закомменченный код, как я писал на предыдущем ревью

2023-01-31 12:46 UTC, Barugoo requested changes
Хорошо, но остались замечания

2023-02-01 15:56 UTC, Perehodko commented on cmd/shortener/main.go
> +		if initialURL == "" {
убрала пока эту проверку

2023-02-06 20:23 UTC, Barugoo commented on cmd/shortener/main.go
> +		fileStorage := storage.NewMemStorage()
давай тогда здесь назовем не `fileStorage`, а `memStorage`, чтобы не вводить в заблуждение

2023-02-06 20:23 UTC, Barugoo commented on cmd/shortener/main.go
> +	fileStorage, err := NewStorage(cfg.FileName)
Здесь тоже самое

2023-02-06 20:23 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Fatal(err)
Давай еще к фаталам писать пояснения, чтобы понятно было где конкретно упали:
```go
log.Fatalf("unable to init new storage: %v", err)

2023-02-06 20:24 UTC, Barugoo commented on cmd/shortener/main.go
> +			http.Error(w, err.Error(), http.StatusInternalServerError)
Здесь `return`

2023-02-06 20:25 UTC, Barugoo commented on cmd/shortener/main.go
> +			panic(err)
Никогда не паникуем в коде хэндлеров (да и вообще в любом коде, где мы можем обработать ошибку без паники):
```go
err := decoder.Decode(&u)
if err != nil {
	http.Error(w, err.Error(), http.StatusBadRequest)
 	return
}

2023-02-06 20:28 UTC, Barugoo commented on cmd/shortener/main.go
> +			http.Error(w, err.Error(), 400)
Давай пользоваться константами пакета `net/http`

2023-02-06 20:29 UTC, Barugoo approved these changes
Работу принимаю, спасибо что подождала ревью!

2023-02-07 07:49 UTC, merged